In [1]:
#Importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Loading our data and taking a look at it

df = pd.read_csv('glassdoor_jobs_cleaned.csv')
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,age,Python_yn,R_yn,Aws_yn,Excel_yn,Spark_yn,job_simp,seniority,desc_len,num_comp
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,...,50,1,0,0,1,0,data scientist,na,2536,0
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,...,39,1,0,0,0,0,data scientist,na,4783,0
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,...,13,1,0,0,1,1,data scientist,na,3461,0
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,58,1,0,0,0,0,data scientist,na,3883,3
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,...,25,1,0,0,1,0,data scientist,na,2728,3

In [3]:
#Feature selection

#df.columns

df_model = df[['avg_salary','Rating','Size','Type of ownership','Industry','Sector','Revenue','num_comp','hourly','employer provided',
             'job_state','same_state','age','Python_yn','Spark_yn','Aws_yn','Excel_yn','job_simp','seniority','desc_len']]

In [4]:
#Transforming categorical features into dummy variables

df_dum = pd.get_dummies(df_model)
df_dum

,avg_salary,Rating,num_comp,hourly,employer provided,same_state,age,Python_yn,Spark_yn,Aws_yn,...,job_simp_analyst,job_simp_data engineer,job_simp_data scientist,job_simp_director,job_simp_manager,job_simp_mle,job_simp_na,seniority_jr,seniority_na,seniority_senior
0,72.0,3.8,0,0,0,0,50,1,0,0,...,0,0,1,0,0,0,0,0,1,0
1,87.5,3.4,0,0,0,0,39,1,0,0,...,0,0,1,0,0,0,0,0,1,0
2,85.0,4.8,0,0,0,1,13,1,1,0,...,0,0,1,0,0,0,0,0,1,0
3,76.5,3.8,3,0,0,1,58,1,0,0,...,0,0,1,0,0,0,0,0,1,0
4,114.5,2.9,3,0,0,1,25,1,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,84.5,3.9,3,0,0,0,193,0,0,1,...,0,0,0,0,0,0,1,0,0,1
738,102.5,4.4,3,0,0,0,17,1,1,1,...,0,1,0,0,0,0,0,0,0,1
739,73.5,2.6,0,0,0,1,39,0,0,0,...,0,0,0,0,0,0,1,0,1,0
740,127.5,3.2,0,0,0,0,-1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
741,93.5,3.6,0,0,0,0,56,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [5]:
#Train test split with 20% test size

from sklearn.model_selection import train_test_split

X = df_dum.drop('avg_salary', axis=1)
y = df_dum[['avg_salary']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [6]:
#Multiple Linear Regression using statsmodels

import statsmodels.api as sm

X_sm = sm.add_constant(X)
model = sm.OLS(y, X_sm)
model.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             avg_salary   R-squared:                       0.708
Model:                            OLS   Adj. R-squared:                  0.638
Method:                 Least Squares   F-statistic:                     10.21
Date:                Sat, 16 Sep 2023   Prob (F-statistic):           1.48e-94
Time:                        13:10:00   Log-Likelihood:                -3311.7
No. Observations:                 742   AIC:                             6909.
Df Residuals:                     599   BIC:                             7568.
Df Model:                         142
Covariance Type:            nonrobust
=====================================================================================================================
                                                        coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
const                                                43.6012      6.720      6.488      0.000      30.404      56.799
Rating                                                3.6051      1.937      1.861      0.063      -0.200       7.410
num_comp                                              2.2511      0.868      2.593      0.010       0.546       3.956
hourly                                              -36.5821      9.173     -3.988      0.000     -54.597     -18.567
employer provided                                    31.3641     11.524      2.722      0.007       8.731      53.997
same_state                                            2.4813      2.619      0.948      0.344      -2.661       7.624
age                                                   0.0348      0.030      1.160      0.246      -0.024       0.094
Python_yn                                             8.1363      2.523      3.224      0.001       3.180      13.092
Spark_yn                                             -0.5715      2.921     -0.196      0.845      -6.307       5.164
Aws_yn                                                1.1228      2.736      0.410      0.682      -4.250       6.496
Excel_yn                                             -0.4020      2.268     -0.177      0.859      -4.855       4.051
desc_len                                             -0.0001      0.001     -0.171      0.864      -0.002       0.001
Size_-1                                              13.6196      8.629      1.578      0.115      -3.328      30.567
Size_1 to 50 employees                                1.1087      6.501      0.171      0.865     -11.659      13.876
Size_10000+ employees                                -2.9049      5.801     -0.501      0.617     -14.297       8.487
Size_1001 to 5000 employees                           6.1218      3.880      1.578      0.115      -1.498      13.741
Size_201 to 500 employees                             2.2418      3.873      0.579      0.563      -5.364       9.848
Size_5001 to 10000 employees                         -3.8783      5.443     -0.713      0.476     -14.568       6.811
Size_501 to 1000 employees                            2.1611      4.059      0.532      0.595      -5.811      10.133
Size_51 to 200 employees                              4.1816      4.422      0.946      0.345      -4.502      12.865
Size_Unknown                                         20.9498     13.993      1.497      0.135      -6.532      48.432
Type of ownership_-1                                 13.6196      8.629      1.578      0.115      -3.328      30.567
Type of ownership_College / University                6.4736     17.737      0.365      0.715     -28.360      41.307
Type of ownership_Company - Private                   8.5803      5.239      1.638      0.102      -1.709      18.869
Type of ownership_Company - Public                   13.2791      5.699      2.330      0.020       2.086      24.472
Type of ownership_Government                        -15.3416     15.290     -1.003      0.316     -45.370      14.687
Type of ownership_Hospital                           -7.1449      9.965     -0.717      0.474     -26.715      12.425
Type of ownership_Nonprofit Organization             -9.8015      6.711     -1.460      0.145     -22.982       3.379
Type of ownership_Other Organization                 -5.9874     14.343     -0.417      0.676     -34.155      22.181
Type of ownership_School / School District           -5.9826     23.791     -0.251      0.802     -52.707      40.742
Type of ownership_Subsidiary or Business Segment     12.7745      6.927      1.844      0.066      -0.829      26.378
Type of ownership_Unknown                            33.1320     28.609      1.158      0.247     -23.053      89.317
Industry_-1                                           5.8383      7.935      0.736      0.462      -9.746      21.422
Industry_Accounting                                   2.5098     13.486      0.186      0.852     -23.976      28.995
Industry_Advertising & Marketing                     11.6481      5.976      1.949      0.052      -0.088      23.384
Industry_Aerospace & Defense                          5.5783      3.109      1.794      0.073      -0.528      11.685
Industry_Architectural & Engineering Services       -32.4236     15.936     -2.035      0.042     -63.720      -1.127
Industry_Auctions & Galleries                         9.3409     22.875      0.408      0.683     -35.585      54.267
Industry_Banks & Credit Unions                      -16.9446      8.045     -2.106      0.036     -32.745      -1.144
Industry_Beauty & Personal Accessories Stores        15.4158     21.561      0.715      0.475     -26.929      57.761
Industry_Biotech & Pharmaceuticals                    6.4294      2.045      3.145      0.002       2.414      10.445
Industry_Brokerage Services                          28.1128     15.522      1.811      0.071      -2.372      58.598
Industry_Colleges & Universities                     10.9486     12.990      0.843      0.400     -14.562      36.460
Industry_Computer Hardware & Software                -0.9246      3.250     -0.285      0.776      -7.307       5.458
Industry_Construction                               -15.5520     10.562     -1.472      0.141     -36.295       5.191
Industry_Consulting                                  12.9278      5.901      2.191      0.029       1.339      24.516
Industry_Consumer Product Rental                     -2.4589     13.017     -0.189      0.850     -28.024      23.106
Industry_Consumer Products Manufacturing             13.8231      9.858      1.402      0.161      -5.538      33.184
Industry_Department, Clothing, & Shoe Stores          4.7171     11.579      0.407      0.684     -18.024      27.458
Industry_Education Training Services                -23.4758     12.525     -1.874      0.061     -48.073       1.122
Industry_Energy                                      -4.1921      7.678     -0.546      0.585     -19.270      10.886
Industry_Enterprise Software & Network Solutions      9.4994      3.592      2.645      0.008       2.445      16.554
Industry_Farm Support Services                       -0.8926     12.652     -0.071      0.944     -25.741      23.956
Industry_Federal Agencies                             8.0706      5.268      1.532      0.126      -2.275      18.416
Industry_Financial Analytics & Research               0.3402      9.196      0.037      0.971     -17.720      18.400
Industry_Financial Transaction Processing           -17.5101     12.894     -1.358      0.175     -42.834       7.813
Industry_Food & Beverage Manufacturing               -3.0947     11.579     -0.267      0.789     -25.836      19.647
Industry_Gambling                                    -9.2525      6.524     -1.418      0.157     -22.065       3.560
Industry_Gas Stations                               -24.3354     15.544     -1.566      0.118     -54.863       6.192
Industry_Health Care Products Manufacturing          21.0157     22.123      0.950      0.343     -22.432      64.464
Industry_Health Care Services & Hospitals             5.9408      2.916      2.037      0.042       0.213      11.668
Industry_Health, Beauty, & Fitness                   -2.2275     17.436     -0.128      0.898     -36.470      32.015
Industry_IT Services                                  1.2100      3.580      0.338      0.736      -5.822       8.242
Industry_Industrial Manufacturing                   -13.8517     12.833     -1.079      0.281     -39.054      11.351
Industry_Insurance Agencies & Brokerages             -3.9062      7.005     -0.558      0.577     -17.664       9.852
Industry_Insurance Carriers                           5.5810      4.489      1.243      0.214      -3.235      14.397
Industry_Internet                                     0.3625      4.513      0.080      0.936      -8.502       9.227
Industry_Investment Banking & Asset Management       35.8709     12.086      2.968      0.003      12.134      59.608
Industry_K-12 Education                              10.0671     14.781      0.681      0.496     -18.962      39.096
Industry_Lending                                     -1.5471      9.860     -0.157      0.875     -20.912      17.818
Industry_Logistics & Supply Chain                     1.4288     13.405      0.107      0.915     -24.897      27.755
Industry_Metals Brokers                              -7.9036     15.608     -0.506      0.613     -38.557      22.750
Industry_Mining                                      -3.5905     17.980     -0.200      0.842     -38.903      31.722
Industry_Motion Picture Production & Distribution    46.0437     19.608      2.348      0.019       7.535      84.552
Industry_Other Retail Stores                         39.9862     21.695      1.843      0.066      -2.621      82.593
Industry_Real Estate                                 -2.3353      4.960     -0.471      0.638     -12.076       7.405
Industry_Religious Organizations                     25.9002     13.715      1.888      0.059      -1.035      52.836
Industry_Research & Development                      -3.1302      6.544     -0.478      0.633     -15.982       9.722
Industry_Security Services                           14.3425      9.791      1.465      0.143      -4.886      33.571
Industry_Social Assistance                          -11.0886     11.786     -0.941      0.347     -34.235      12.058
Industry_Sporting Goods Stores                      -37.3097     17.862     -2.089      0.037     -72.389      -2.230
Industry_Staffing & Outsourcing                      -5.3747     11.019     -0.488      0.626     -27.014      16.265
Industry_Stock Exchanges                            -15.1212      7.891     -1.916      0.056     -30.619       0.377
Industry_TV Broadcast & Cable Networks                0.0330     15.540      0.002      0.998     -30.486      30.552
Industry_Telecommunications Manufacturing             4.1691     13.669      0.305      0.760     -22.676      31.014
Industry_Telecommunications Services                  0.1287     11.268      0.011      0.991     -22.000      22.258
Industry_Transportation Equipment Manufacturing     -19.4469     23.723     -0.820      0.413     -66.037      27.143
Industry_Transportation Management                  -20.6995     14.025     -1.476      0.141     -48.244       6.845
Industry_Travel Agencies                             -5.5190      5.255     -1.050      0.294     -15.840       4.802
Industry_Trucking                                    22.8371     19.852      1.150      0.250     -16.151      61.825
Industry_Video Games                                -30.1817     14.428     -2.092      0.037     -58.518      -1.845
Industry_Wholesale                                   -2.2256     13.108     -0.170      0.865     -27.969      23.518
Sector_-1                                             5.8383      7.935      0.736      0.462      -9.746      21.422
Sector_Accounting & Legal                             2.5098     13.486      0.186      0.852     -23.976      28.995
Sector_Aerospace & Defense                            5.5783      3.109      1.794      0.073      -0.528      11.685
Sector_Agriculture & Forestry                        -0.8926     12.652     -0.071      0.944     -25.741      23.956
Sector_Arts, Entertainment & Recreation              -9.2525      6.524     -1.418      0.157     -22.065       3.560
Sector_Biotech & Pharmaceuticals                      6.4294      2.045      3.145      0.002       2.414      10.445
Sector_Business Services                             -4.2357      4.213     -1.005      0.315     -12.509       4.038
Sector_Construction, Repair & Maintenance           -15.5520     10.562     -1.472      0.141     -36.295       5.191
Sector_Consumer Services                             -4.6864      9.426     -0.497      0.619     -23.199      13.826
Sector_Education                                     -2.4602      6.838     -0.360      0.719     -15.889      10.968
Sector_Finance                                       13.2008      4.519      2.921      0.004       4.327      22.075
Sector_Government                                     8.0706      5.268      1.532      0.126      -2.275      18.416
Sector_Health Care                                    5.9408      2.916      2.037      0.042       0.213      11.668
Sector_Information Technology                        10.1474      2.785      3.644      0.000       4.678      15.617
Sector_Insurance                                      1.6747      3.945      0.425      0.671      -6.072       9.422
Sector_Manufacturing                                 -1.5546      6.909     -0.225      0.822     -15.124      12.014
Sector_Media                                         15.8949      8.725      1.822      0.069      -1.240      33.030
Sector_Mining & Metals                              -11.4941     10.725     -1.072      0.284     -32.558       9.570
Sector_Non-Profit                                    14.8115      8.900      1.664      0.097      -2.667      32.290
Sector_Oil, Gas, Energy & Utilities                  -4.1921      7.678     -0.546      0.585     -19.270      10.886
Sector_Real Estate                                   -2.3353      4.960     -0.471      0.638     -12.076       7.405
Sector_Retail                                         7.8149      7.178      1.089      0.277      -6.283      21.912
Sector_Telecommunications                             4.2978      7.813      0.550      0.582     -11.046      19.641
Sector_Transportation & Logistics                     3.5664      8.050      0.443      0.658     -12.244      19.377
Sector_Travel & Tourism                              -5.5190      5.255     -1.050      0.294     -15.840       4.802
Revenue_$1 to $2 billion (USD)                        2.9065      4.800      0.605      0.545      -6.521      12.334
Revenue_$1 to $5 million (USD)                       -5.6696     10.966     -0.517      0.605     -27.206      15.866
Revenue_$10 to $25 million (USD)                     -4.8466      5.228     -0.927      0.354     -15.114       5.421
Revenue_$10+ billion (USD)                           10.4141      6.399      1.628      0.104      -2.152      22.981
Revenue_$100 to $500 million (USD)                   -5.1303      4.064     -1.262      0.207     -13.112       2.851
Revenue_$2 to $5 billion (USD)                        0.2080      6.283      0.033      0.974     -12.132      12.548
Revenue_$25 to $50 million (USD)                     -5.2661      5.368     -0.981      0.327     -15.809       5.276
Revenue_$5 to $10 billion (USD)                       6.6867      7.865      0.850      0.396      -8.759      22.133
Revenue_$5 to $10 million (USD)                      31.8413      8.323      3.826      0.000      15.496      48.186
Revenue_$50 to $100 million (USD)                     5.3703      4.974      1.080      0.281      -4.398      15.138
Revenue_$500 million to $1 billion (USD)             -1.9413      5.298     -0.366      0.714     -12.346       8.463
Revenue_-1                                           13.6196      8.629      1.578      0.115      -3.328      30.567
Revenue_Less than $1 million (USD)                   -4.2630     15.212     -0.280      0.779     -34.139      25.613
Revenue_Unknown / Non-Applicable                     -0.3283      3.081     -0.107      0.915      -6.379       5.722
job_state_ AL                                        -6.0058     10.467     -0.574      0.566     -26.563      14.551
job_state_ AZ                                       -14.0275      8.626     -1.626      0.104     -30.969       2.914
job_state_ CA                                        26.7197      3.156      8.467      0.000      20.522      32.918
job_state_ CO                                         7.8529      8.300      0.946      0.344      -8.448      24.153
job_state_ CT                                       -23.7326     11.366     -2.088      0.037     -46.056      -1.410
job_state_ DC                                        13.7357      7.936      1.731      0.084      -1.850      29.322
job_state_ DE                                         9.2463     13.872      0.667      0.505     -17.997      36.489
job_state_ FL                                       -15.8810      7.637     -2.080      0.038     -30.879      -0.883
job_state_ GA                                       -18.5367     10.118     -1.832      0.067     -38.407       1.334
job_state_ IA                                        -2.4859     12.448     -0.200      0.842     -26.932      21.960
job_state_ ID                                       -24.3798     18.301     -1.332      0.183     -60.322      11.562
job_state_ IL                                         9.0956      5.035      1.807      0.071      -0.793      18.984
job_state_ IN                                       -10.3063      8.818     -1.169      0.243     -27.624       7.012
job_state_ KS                                       -15.1212      7.891     -1.916      0.056     -30.619       0.377
job_state_ KY                                        19.8151     12.362      1.603      0.109      -4.463      44.093
job_state_ LA                                        -6.2195     13.080     -0.475      0.635     -31.908      19.469
job_state_ MA                                         2.8321      3.874      0.731      0.465      -4.776      10.440
job_state_ MD                                         7.8101      4.926      1.586      0.113      -1.864      17.484
job_state_ MI                                         7.4898     12.333      0.607      0.544     -16.732      31.711
job_state_ MN                                         8.3551     17.271      0.484      0.629     -25.563      42.274
job_state_ MO                                         9.8899      9.858      1.003      0.316      -9.470      29.250
job_state_ NC                                        -3.8930      6.753     -0.576      0.565     -17.155       9.370
job_state_ NE                                        -3.1512     13.459     -0.234      0.815     -29.584      23.281
job_state_ NJ                                         1.1983      6.825      0.176      0.861     -12.205      14.602
job_state_ NM                                       -30.4763     14.488     -2.104      0.036     -58.930      -2.023
job_state_ NY                                         5.8270      4.026      1.447      0.148      -2.080      13.734
job_state_ OH                                        -0.4478      8.177     -0.055      0.956     -16.507      15.612
job_state_ OR                                         2.3883     12.656      0.189      0.850     -22.468      27.244

In [12]:
#Multiple Linear Regression using sklearn

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lm = LinearRegression()
lm.fit(X_train, y_train)
#lm.score(X_train, y_train)

np.mean(cross_val_score(lm, X_train, y_train, scoring='neg_mean_absolute_error', cv=3))

-20.77023361366756

In [8]:
#Lasso Regression

from sklearn.linear_model import Lasso

lm_l = Lasso(alpha=.13)
lm_l.fit(X_train,y_train)
np.mean(cross_val_score(lm_l,X_train,y_train, scoring = 'neg_mean_absolute_error', cv= 3))

-19.26251583392883

In [9]:
#Trying to find the best alpha hyperparameter manually for Lasso Model

alpha = []
error = []

for i in range(1,100):
    alpha.append(i/100)
    lml = Lasso(alpha=(i/100))
    error.append(np.mean(cross_val_score(lml,X_train,y_train, scoring = 'neg_mean_absolute_error', cv= 3)))
    
#plt.plot(alpha,error)

err = tuple(zip(alpha,error))
df_err = pd.DataFrame(err, columns = ['alpha','error'])
df_err[df_err.error == max(df_err.error)]

    alpha      error
12   0.13 -19.262516

In [13]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(X_train, y_train)
np.mean(cross_val_score(rf,X_train,y_train,scoring = 'neg_mean_absolute_error', cv= 3))

C:\Users\ASUS\AppData\Local\Temp\ipykernel_7772\3499017534.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

-15.13325437112239

In [ ]:
#Tuning Random Forest Model using Grid Search

from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':range(10,300,10), 'criterion':('mse','mae'), 'max_features':('auto','sqrt','log2')}

gs = GridSearchCV(rf, parameters, scoring='neg_mean_absolute_error', cv=3)
gs.fit(X_train, y_train)

gs.best_score_
gs.best_estimator_

In [15]:
# test ensembles 

from sklearn.metrics import mean_absolute_error

tpred_lm = lm.predict(X_test)
tpred_lml = lm_l.predict(X_test)
tpred_rf = rf.predict(X_test)
#tpred_rf = gs.best_estimator_.predict(X_test)

print("Mean absolute error using linear regression model:", mean_absolute_error(y_test,tpred_lm))
print("Mean absolute error using lasso regression model:", mean_absolute_error(y_test,tpred_lml))
print("Mean absolute error using random forest model:", mean_absolute_error(y_test,tpred_rf))

#Here, we used a combination of predictions of both linear regression and random forest to get a better result
#print("Mean absolute error using a combination of predictions of linear regression and random forest models:", mean_absolute_error(y_test,(tpred_lm+tpred_rf)/2))

Mean absolute error using linear regression model: 24541705.303505123
Mean absolute error using lasso regression model: 19.66540217867269
Mean absolute error using random forest model: 10.955738255033557

In [16]:
#Saving the model that gives us best results after being trained on data for later use

import pickle

#pickl = {'model': gs.best_estimator_}
pickl = {'model' : rf}
pickle.dump(pickl, open( 'model_file' + ".p", "wb" ))

In [18]:
#Load our model again if we need it

file_name = "model_file.p"
with open(file_name, 'rb') as pickled:
    data = pickle.load(pickled)
    model = data['model']

model.predict(np.array(list(X_test.iloc[1,:])).reshape(1,-1))[0]

#list(X_test.iloc[1,:])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

52.6